version: '3'
services:
  updater:
    container_name: dependency_explorer
    image: whoisacat/dependency-explorer:entrypoint-script
    privileged: true
    restart: on-failure
    volumes:
      - /tmp/dependency_explorer:/files